---

kind: pipeline
name: Bulk run Azure pipelines

platform:
  os: linux
  arch: amd64

steps:
- name: Run build pipelines
  image: dclocal/drone-azure-pipelines:1.0.0
  settings:
    action: build
    definitions:
      - build_definition_id_1
      - build_definition_id_2
    organization: organization
    project: project
    user: username@domain.com
    secret:
      from_secret: az_secret

- name: Create a new release for selected stages
  image: dclocal/drone-azure-pipelines:1.0.0
  settings:
    action: release
    check_build_state: true
    definitions:
      - release_definition_id_1
      - release_definition_id_2
    stages:
      - development
      - test
    organization: organization
    project: project
    user: username@domain.com
    secret:
      from_secret: az_secret