---

kind: pipeline
name: Bulk run Azure pipelines

platform:
  os: linux
  arch: amd64

steps:
- name: Queue selected build pipelines
  image: dclocal/drone-azure-pipelines:1.0.0
  settings:
    action: queue_build
    skip: true
    definitions:
      - build_definition_id_1
      - build_definition_id_2
    organization: organization
    project: project
    user: username@domain.com
    secret:
      from_secret: azure_secret

- name: Create a new release for selected environments
  image: dclocal/drone-azure-pipelines:1.0.0
  settings:
    action: release
    skip: true
    definitions:
      - release_definition_id_1
      - release_definition_id_2
    environments:
      - development
      - test
    organization: organization
    project: project
    user: username@domain.com
    secret:
      from_secret: azure_secret